### ISSUE TITLE
Dev Tooling Upgrade

### ISSUE THREAD

**Issue by smithad15** [angular-redux/platform#19]

**Comment by beac0n** [comment]
Is this issue related to this error message:

> `window.devToolsExtension` is deprecated in favor of `window.__REDUX_DEVTOOLS_EXTENSION__`, and will be removed in next version of Redux DevTools:

https://github.com/zalmoxisus/redux-devtools-extension#usage

**Comment by smithad15** [comment]
It's not, but I will add a new issue for that.

**Comment by smithad15** [comment]
See #56 for progress on the above
