### ISSUE TITLE
Install Guidelines for angular-redux

### ISSUE THREAD

**Issue by Prat041192** [angular-redux/platform#42]
I am trying to install angular-redux/store, angular-redux/routerm, and angular-redux/form in my Angular project ( `"@angular/core": "^6.1.6",` ).
My package.json show 
  `
 "@angular-redux/form": "github:angular-redux/form",
 "@angular-redux/router": "github:angular-redux/router",
 "@angular-redux/store": "github:angular-redux/store",
`

redux version ( ` "redux": "^4.0.0", `)
mentioned 3 entries but whenever I build the project It gives me an error 'cannot find module XXX'.

Is there any specific thing that I am missing or is there any version miss match?

**Comment by smithad15** [comment]
That error is generally related to how your modules are registered or imported in the source code. Due to the amount of time passed with this issue, I hope that you were able to find a solution. If not, please provide more details or a reproduction on StackBlitz or similar
