### ISSUE TITLE
[Question] Angular 7 support

### ISSUE THREAD

**Issue by chunghha** [angular-redux/platform#48]
I am sorry to ask this kind of questions to Issues here.

@smithad15 could you answer what's being planned to support Angular 7 with these packages? ( I know the store v.9 works fine with Angular 7 except peer dependency warning on npm installation. ) If you could, it would be a great help for me to schedule our production updates to Angular 7.

**Comment by HarelM** [comment]
Same here.

**Comment by smithad15** [comment]
As it is now January, you can probably guess that the grand plans of getting v10 of this library released along-side Angular 7 have come and gone. Once the work of upgrading the example app has been completed (see https://github.com/angular-redux/platform/tree/upgrade-angular-7 for current progress) we will cut v10. Please do continue to use v9 despite the dependency warning

**Comment by chunghha** [comment]
@smithad15 thanks for keeping me posted.
