### ISSUE TITLE
Facilitate class instead of switch cases

### ISSUE THREAD

**Issue by HarelM** [angular-redux/platform#49]
Hi,

I have written the following decorator in order to be able to use classes instead of pure functions and reduce switch cases complexity.
I think it can be a nice addition to this library.
Please let me know what you think.
Most of the code is written here:
https://stackblitz.com/edit/angular-redux-undo-decorator?file=src%2Fapp%2Ftyped-reducer.ts
Example can be seen here:
https://stackblitz.com/edit/angular-redux-undo-decorator

**Comment by smithad15** [comment]
Thanks for presenting this as an option to add to the library. We are going to decline adding it into this library since the utility has an application with more than just Angular code. I would encourage you to create a library of your own and add it to the Redux ecosystem at large. Best of luck!
