### ISSUE TITLE
Example @angular-redux/store^9 + redux-observable^1.0.0

### ISSUE THREAD

**Issue by Sluchaika** [angular-redux/platform#54]
Hello! Where I can find example with @angular-redux/store^9 + redux-observable^1.0.0 ?

**Comment by wtho** [comment]
I created a minimal example [on stackblitz](https://stackblitz.com/edit/angularv7-redux-simple-setup). (Angular v7, rxjs v6, @angular-redux/store v9, redux-observable v1, redux v4)

Feel free to check it out, it is way smaller and simpler than the example app.
