### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by fvilers** [angular-redux/platform#78]
Dear maintainer,

I'm using this library on a corporate level and I was wondering if the project is still alive. It's been 3 months since the last commit. There's an interesting PR open since January (#72) and nothing seems to move here.

I have a piece of code I'd like to submit too, but I'm now considering to publish it under its own package, to ensure it will be accessible to the rest of the community.

Please, give us some news. If you don't feel to maintain it further, or don't have the time, consider transferring ownership to someone else.

Thanks for reading this ;-)

**Comment by ralfhauser** [comment]
If the project were dead, what are the alternatives to get the same funcitonality ?

**Comment by fvilers** [comment]
I hope it isn't. There's another library to use Redux with Angular, which is https://github.com/ngrx/platform

**Comment by smithad15** [comment]
![giphy](https://user-images.githubusercontent.com/6526084/57166245-9196a800-6dc7-11e9-9411-3a91f9b4f1f4.gif)
