### ISSUE TITLE
Class NgRedux incorrectly implements interface RootState

### ISSUE THREAD

**Issue by doanthai** [angular-redux/platform#93]
### This is a...

- [ ] feature request
- [x] bug report
- [ ] usage question

### What toolchain are you using for transpilation/bundling?

- [x] @angular/cli
- [ ] Custom @ngTools/webpack
- [ ] Raw `ngc`
- [ ] SystemJS
- [ ] Rollup
- [ ] Other

### Environment

NodeJS Version: 10.15.3
Typescript Version: 3.4.1
Angular Version: 8.0
@angular-redux/store version: ^10.0.0
@angular/cli version: (if applicable)
OS: Ubuntu 16.04

### Stack Trace/Error Message:

`ERROR in node_modules/@angular-redux/store/components/ng-redux.d.ts(10,31): error TS2420: Class 'NgRedux<RootState>' incorrectly implements interface 'ObservableStore<RootState>'.
      Property '[Symbol.observable]' is missing in type 'NgRedux<RootState>' but required in type 'ObservableStore<RootState>'.`

### Additional Notes:

I write code base on your example-app but when run `ng serve` failed. What do I do to fix that or wait next version your?

Thanks.

**Comment by JackSchaible** [comment]
Same issue here. Only a problem after attempting to upgrade from Angular 7 to 8.

**Comment by JackSchaible** [comment]
Apparently, this is an issue with redux@4.0.3 (and possibly 4.0.2?). I downgraded my redux package to 4.0.1, and it works fine now.

**Comment by doanthai** [comment]
Thanks @JackSchaible, you right I use redux@^4.0.2 and I try change redux version to ^4.0.1 but it isn't working until it's 4.0.1
